criei a classe condicional, e um tipo de plano
Rafael-S-Muniz/RafaFlix pull request #4
Opened 2024-02-16 21:22 UTC by Rafael-S-Muniz

2024-02-16 21:38 UTC, lucasleonor commented on src/Condicional.java
> +}
Parece que ta com problema de formatacao de novo... 😬

2024-02-16 21:40 UTC, lucasleonor requested changes

2024-02-16 21:40 UTC, lucasleonor commented on src/Condicional.java
> +        boolean incluidoNoPlano = false;
talvez renomear para `incluidoNoPlanoBase`?

2024-02-16 21:40 UTC, lucasleonor commented on src/Condicional.java
> +}
Parece que ta com problema de formatacao de novo... 😬

2024-02-16 21:41 UTC, lucasleonor commented
Por que vc criou uma nova classe no lugar de so editar a outra? Elas parecem ser bem similares 🤔

2024-02-16 21:50 UTC, Rafael-S-Muniz commented
> Por que vc criou uma nova classe no lugar de so editar a outra? Elas parecem ser bem similares 🤔

To criando esse programa conforme to aprendendo na aula, então no futuro vai mudar

2024-02-19 13:41 UTC, lucasleonor approved these changes

2024-02-19 19:03 UTC, merged